[package]
name = "live-wallpapers"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.6"
rgb = "0.8.36"
winapi = { version = "0.3.9", features = ["winuser", "processthreadsapi", "libloaderapi", "errhandlingapi", "impl-default"] }
