[package]
name = "live-wallpapers"
version = "0.1.0"
edition = "2021"

[dependencies]
micromath = { version = "2.0.0", features = ["vector"] }
rand = "0.8.5"
winapi = { version = "0.3.9", features = ["winuser", "processthreadsapi", "libloaderapi", "errhandlingapi", "impl-default"] }
